import type { MasterSignal } from './types.js';

export const MASTER_SIGNALS: MasterSignal[] = [
  // ============================================================
  // Sales-Led Signals (tag: sales_led, categoryOrder 1-19)
  // ============================================================
  {
    signalName: 'ICP Fit Score Hit',
    whyItMatters: 'They match your target profile perfectly',
    strength: 'high',
    tag: 'sales_led',
    channel: 'dark_funnel',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Prioritize accounts that match 4+ ICP attributes. Route to assigned AE immediately.',
    categoryOrder: 1,
  },
  {
    signalName: 'Ideal ACV Range Detected',
    whyItMatters: 'Deal size matches your sweet spot',
    strength: 'high',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Use ACV-matched case studies and ROI models in outreach.',
    categoryOrder: 2,
  },
  {
    signalName: 'Multi-Thread Opportunity',
    whyItMatters: 'Multiple stakeholders showing interest',
    strength: 'high',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Map the buying committee. Create role-specific content threads.',
    categoryOrder: 3,
  },
  {
    signalName: 'Executive Sponsor Identified',
    whyItMatters: 'C-suite is aware of your category',
    strength: 'high',
    tag: 'sales_led',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 4,
  },
  {
    signalName: 'Budget Cycle Alignment',
    whyItMatters: 'Their fiscal planning matches your sales cycle',
    strength: 'high',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Time outreach to 6-8 weeks before fiscal year end.',
    categoryOrder: 5,
  },
  {
    signalName: 'Contract Renewal Window',
    whyItMatters: 'Existing vendor contract coming up for renewal',
    strength: 'high',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Initiate outreach 90 days before renewal. Lead with competitor comparison.',
    categoryOrder: 6,
  },
  {
    signalName: 'Expansion Revenue Signal',
    whyItMatters: 'Current customer showing growth indicators',
    strength: 'medium',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 7,
  },
  {
    signalName: 'New Budget Allocation',
    whyItMatters: 'Fresh budget approved for your category',
    strength: 'high',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'bottom_conversion',
    hasPlaybook: false,
    categoryOrder: 8,
  },
  {
    signalName: 'Procurement Process Started',
    whyItMatters: 'Active buying process underway',
    strength: 'high',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'bottom_conversion',
    hasPlaybook: false,
    categoryOrder: 9,
  },
  {
    signalName: 'Champion Identified',
    whyItMatters: 'Internal advocate discovered',
    strength: 'high',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Arm the champion with ROI calculator and internal pitch deck.',
    categoryOrder: 10,
  },
  {
    signalName: 'Pain Point Articulated',
    whyItMatters: 'Prospect explicitly described the problem you solve',
    strength: 'high',
    tag: 'sales_led',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Mirror their exact language in follow-up. Reference specific pain in subject line.',
    categoryOrder: 11,
  },
  {
    signalName: 'RFP/RFI Issued',
    whyItMatters: 'Formal buying process initiated',
    strength: 'high',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'bottom_conversion',
    hasPlaybook: false,
    categoryOrder: 12,
  },
  {
    signalName: 'Inbound Demo Request',
    whyItMatters: 'Direct hand-raise',
    strength: 'high',
    tag: 'sales_led',
    channel: 'website',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Response within 5 minutes. Assign to AE with matching vertical expertise.',
    categoryOrder: 13,
  },
  {
    signalName: 'Sales Qualified Lead',
    whyItMatters: 'Meets all qualification criteria',
    strength: 'high',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'bottom_conversion',
    hasPlaybook: false,
    categoryOrder: 14,
  },
  {
    signalName: 'Pricing Page Visit',
    whyItMatters: 'Evaluating cost',
    strength: 'medium',
    tag: 'sales_led',
    channel: 'website',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Trigger immediate AE outreach with ROI framework.',
    categoryOrder: 15,
  },
  {
    signalName: 'Case Study Download',
    whyItMatters: 'Seeking social proof',
    strength: 'medium',
    tag: 'sales_led',
    channel: 'website',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 16,
  },
  {
    signalName: 'Competitive Comparison Viewed',
    whyItMatters: 'Actively comparing vendors',
    strength: 'high',
    tag: 'sales_led',
    channel: 'website',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Send targeted competitive battlecard within 24 hours.',
    categoryOrder: 17,
  },
  {
    signalName: 'Proposal Requested',
    whyItMatters: 'Deep in buying process',
    strength: 'high',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'bottom_conversion',
    hasPlaybook: false,
    categoryOrder: 18,
  },
  {
    signalName: 'Trial Started',
    whyItMatters: 'Hands-on evaluation',
    strength: 'high',
    tag: 'sales_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Day 1: Welcome + quick win guide. Day 3: Check-in. Day 7: Use case review.',
    categoryOrder: 19,
  },

  // ============================================================
  // Product-Led Signals (tag: product_led, categoryOrder 1-19)
  // ============================================================
  {
    signalName: 'Free Tier Signup',
    whyItMatters: 'Top of product-led funnel',
    strength: 'low',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 1,
  },
  {
    signalName: 'Feature Adoption Spike',
    whyItMatters: 'Deep product engagement happening',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'When >3 features adopted in a week, trigger CS outreach with advanced use cases.',
    categoryOrder: 2,
  },
  {
    signalName: 'Usage Threshold Breach',
    whyItMatters: 'Hitting free tier limits',
    strength: 'high',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Auto-trigger upgrade notification. Have AE ready with custom pricing.',
    categoryOrder: 3,
  },
  {
    signalName: 'Team Invite Sent',
    whyItMatters: 'Organic expansion within the org',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'When 3+ invites sent, offer team onboarding session.',
    categoryOrder: 4,
  },
  {
    signalName: 'Integration Connected',
    whyItMatters: 'Embedding into their workflow',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 5,
  },
  {
    signalName: 'API Key Generated',
    whyItMatters: 'Developer adoption signal',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 6,
  },
  {
    signalName: 'Power User Emergence',
    whyItMatters: 'Someone is going deep',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Identify power user, offer advanced training, recruit as champion.',
    categoryOrder: 7,
  },
  {
    signalName: 'Workspace Created',
    whyItMatters: 'Setting up for real use',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 8,
  },
  {
    signalName: 'Export Data Requested',
    whyItMatters: 'Your product is now the source of truth',
    strength: 'high',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'bottom_conversion',
    hasPlaybook: false,
    categoryOrder: 9,
  },
  {
    signalName: 'Billing Info Added',
    whyItMatters: 'Purchase intent confirmed',
    strength: 'high',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: "Immediate AE assignment. This is a hot lead — don't let it cool.",
    categoryOrder: 10,
  },
  {
    signalName: 'Usage Pattern Change',
    whyItMatters: 'Workflow shift detected',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 11,
  },
  {
    signalName: 'Advanced Feature Discovery',
    whyItMatters: 'Exploring premium capabilities',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 12,
  },
  {
    signalName: 'Collaboration Feature Used',
    whyItMatters: 'Multi-user engagement',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 13,
  },
  {
    signalName: 'Dashboard/Report Created',
    whyItMatters: 'Getting value from analytics',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 14,
  },
  {
    signalName: 'Notification Preferences Set',
    whyItMatters: 'Planning to come back',
    strength: 'low',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 15,
  },
  {
    signalName: 'Support Ticket from Free User',
    whyItMatters: 'Engaged enough to ask for help',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 16,
  },
  {
    signalName: 'Mobile App Install',
    whyItMatters: 'Multi-device commitment',
    strength: 'low',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 17,
  },
  {
    signalName: 'Template/Workflow Cloned',
    whyItMatters: 'Operationalizing your product',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 18,
  },
  {
    signalName: 'Custom Field Created',
    whyItMatters: 'Adapting product to their process',
    strength: 'medium',
    tag: 'product_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 19,
  },

  // ============================================================
  // Nearbound Signals (tag: nearbound, categoryOrder 1-10)
  // ============================================================
  {
    signalName: 'Partner Referral Received',
    whyItMatters: 'Trusted third-party endorsement',
    strength: 'high',
    tag: 'nearbound',
    channel: 'community',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Priority fast-track. Warm intro template. Update partner on progress within 48 hours.',
    categoryOrder: 1,
  },
  {
    signalName: 'Shared Customer Overlap',
    whyItMatters: "Your partner's customer needs you",
    strength: 'medium',
    tag: 'nearbound',
    channel: 'crm',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 2,
  },
  {
    signalName: 'Technology Ecosystem Fit',
    whyItMatters: 'They use your integration partners',
    strength: 'medium',
    tag: 'nearbound',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 3,
  },
  {
    signalName: 'Investor Portfolio Match',
    whyItMatters: 'VC/PE portfolio company in your ICP',
    strength: 'medium',
    tag: 'nearbound',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Request warm intro through investor relations. Lead with portfolio company success story.',
    categoryOrder: 4,
  },
  {
    signalName: 'Agency/Consultant Recommendation',
    whyItMatters: 'Trusted advisor is suggesting you',
    strength: 'high',
    tag: 'nearbound',
    channel: 'community',
    funnelStage: 'bottom_conversion',
    hasPlaybook: false,
    categoryOrder: 5,
  },
  {
    signalName: 'Former Customer at New Company',
    whyItMatters: 'Champion has moved',
    strength: 'high',
    tag: 'nearbound',
    channel: 'crm',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Reach out within 2 weeks of role change. Offer expedited onboarding.',
    categoryOrder: 6,
  },
  {
    signalName: 'Board Member Connection',
    whyItMatters: 'Governance-level access',
    strength: 'medium',
    tag: 'nearbound',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 7,
  },
  {
    signalName: 'Industry Analyst Mention',
    whyItMatters: 'Third-party credibility boost',
    strength: 'medium',
    tag: 'nearbound',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 8,
  },
  {
    signalName: 'Co-Selling Opportunity',
    whyItMatters: 'Joint value proposition possible',
    strength: 'high',
    tag: 'nearbound',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 9,
  },
  {
    signalName: 'Customer Advisory Board Member',
    whyItMatters: 'Existing customer with influence',
    strength: 'medium',
    tag: 'nearbound',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 10,
  },

  // ============================================================
  // Event Signals (tag: event, categoryOrder 1-8)
  // ============================================================
  {
    signalName: 'Webinar Attended',
    whyItMatters: 'Willingly spent time learning about your space',
    strength: 'medium',
    tag: 'event',
    channel: 'website',
    funnelStage: 'top_awareness',
    hasPlaybook: true,
    playbook: 'Follow up within 24 hours with relevant resource. Segment by engagement level.',
    categoryOrder: 1,
  },
  {
    signalName: 'Conference Booth Visit',
    whyItMatters: 'In-person engagement',
    strength: 'medium',
    tag: 'event',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Badge scan → 24-hour personalized follow-up with session-specific content.',
    categoryOrder: 2,
  },
  {
    signalName: 'Speaking Engagement Attended',
    whyItMatters: 'Listened to your thought leadership',
    strength: 'medium',
    tag: 'event',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 3,
  },
  {
    signalName: 'Workshop Participated',
    whyItMatters: 'Invested significant time',
    strength: 'high',
    tag: 'event',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Send workshop materials + personalized action plan within 24 hours.',
    categoryOrder: 4,
  },
  {
    signalName: 'Virtual Event Registration',
    whyItMatters: 'Showed intent',
    strength: 'low',
    tag: 'event',
    channel: 'website',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 5,
  },
  {
    signalName: 'Post-Event Survey Completed',
    whyItMatters: 'Extra engagement after event',
    strength: 'medium',
    tag: 'event',
    channel: 'website',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 6,
  },
  {
    signalName: 'Networking Session Attended',
    whyItMatters: 'Seeking peer connections',
    strength: 'medium',
    tag: 'event',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 7,
  },
  {
    signalName: 'Award/Recognition Nomination',
    whyItMatters: 'Industry recognition moment',
    strength: 'low',
    tag: 'event',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 8,
  },

  // ============================================================
  // Competitor Signals (tag: competitor, categoryOrder 1-12)
  // ============================================================
  {
    signalName: 'Competitor Pricing Change',
    whyItMatters: 'Disruption in their current vendor relationship',
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Create targeted comparison showing your value/price advantage.',
    categoryOrder: 1,
  },
  {
    signalName: 'Competitor Product Issue',
    whyItMatters: 'Their vendor is failing them',
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Time outreach within 48 hours. Lead with stability and reliability messaging.',
    categoryOrder: 2,
  },
  {
    signalName: 'Competitor Acquisition',
    whyItMatters: 'Market consolidation creates uncertainty',
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Reach out to affected customers within 1 week with migration offer.',
    categoryOrder: 3,
  },
  {
    signalName: 'Competitor Employee Exodus',
    whyItMatters: 'Instability at their vendor',
    strength: 'medium',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 4,
  },
  {
    signalName: 'Competitor Feature Gap',
    whyItMatters: "Unmet need their vendor can't fill",
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 5,
  },
  {
    signalName: 'G2/Capterra Review Spike',
    whyItMatters: 'Active vendor evaluation happening',
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Monitor competitor review sentiment. Outreach to negative reviewers.',
    categoryOrder: 6,
  },
  {
    signalName: 'Switching Signal Detected',
    whyItMatters: 'Active migration interest',
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Priority routing. Offer migration assistance and competitive pricing.',
    categoryOrder: 7,
  },
  {
    signalName: 'Competitor Contract Ending',
    whyItMatters: 'Renewal decision approaching',
    strength: 'high',
    tag: 'competitor',
    channel: 'crm',
    funnelStage: 'bottom_conversion',
    hasPlaybook: false,
    categoryOrder: 8,
  },
  {
    signalName: 'Technology Stack Conflict',
    whyItMatters: "Their current tool doesn't play well with others",
    strength: 'medium',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 9,
  },
  {
    signalName: 'Competitor Downtime/Outage',
    whyItMatters: 'Reliability failure at competitor',
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 10,
  },
  {
    signalName: 'Market Analyst Report',
    whyItMatters: 'Industry evaluation happening',
    strength: 'medium',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 11,
  },
  {
    signalName: 'Competitor Sunset Announcement',
    whyItMatters: 'Their current solution is being deprecated',
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'bottom_conversion',
    hasPlaybook: false,
    categoryOrder: 12,
  },

  // ============================================================
  // Community-Led Signals (tag: community_led, categoryOrder 1-32)
  // ============================================================
  {
    signalName: 'Community Forum Active',
    whyItMatters: 'Engaged in your ecosystem',
    strength: 'medium',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: true,
    playbook: 'Identify active members. Offer exclusive access or early features.',
    categoryOrder: 1,
  },
  {
    signalName: 'Open Source Contributor',
    whyItMatters: 'Building with your technology',
    strength: 'medium',
    tag: 'community_led',
    channel: 'open_source',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Recognize contribution. Offer commercial license discussion.',
    categoryOrder: 2,
  },
  {
    signalName: 'Social Media Engagement',
    whyItMatters: 'Public interaction with your brand',
    strength: 'low',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 3,
  },
  {
    signalName: 'Blog/Content Subscriber',
    whyItMatters: 'Consistent content consumption',
    strength: 'low',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 4,
  },
  {
    signalName: 'User Group Member',
    whyItMatters: 'Part of your community',
    strength: 'medium',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 5,
  },
  {
    signalName: 'Meetup Organizer',
    whyItMatters: 'Community leadership',
    strength: 'medium',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 6,
  },
  {
    signalName: 'Podcast Listener',
    whyItMatters: 'Long-form content engagement',
    strength: 'low',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 7,
  },
  {
    signalName: 'Newsletter Engagement',
    whyItMatters: 'Regular reader with high open rate',
    strength: 'low',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 8,
  },
  {
    signalName: 'Slack/Discord Community Active',
    whyItMatters: 'Real-time community engagement',
    strength: 'medium',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 9,
  },
  {
    signalName: 'GitHub Stars/Follows',
    whyItMatters: 'Developer interest signal',
    strength: 'low',
    tag: 'community_led',
    channel: 'open_source',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 10,
  },
  {
    signalName: 'Developer Documentation Views',
    whyItMatters: 'Technical evaluation',
    strength: 'medium',
    tag: 'community_led',
    channel: 'website',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'When dev docs + API docs viewed, route to technical sales team.',
    categoryOrder: 11,
  },
  {
    signalName: 'Stack Overflow Mentions',
    whyItMatters: 'Developers discussing your product',
    strength: 'medium',
    tag: 'community_led',
    channel: 'open_source',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 12,
  },
  {
    signalName: 'Beta Program Application',
    whyItMatters: 'Wants early access',
    strength: 'high',
    tag: 'community_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Fast-track beta access. Assign dedicated CS contact.',
    categoryOrder: 13,
  },
  {
    signalName: 'Customer Story Shared',
    whyItMatters: 'Organic advocacy',
    strength: 'medium',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 14,
  },
  {
    signalName: 'UGC Created',
    whyItMatters: 'User-generated content about your product',
    strength: 'medium',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 15,
  },
  {
    signalName: 'Certification Program Enrolled',
    whyItMatters: 'Investing in your ecosystem',
    strength: 'high',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Offer enterprise features aligned to certification path.',
    categoryOrder: 16,
  },
  {
    signalName: 'Referral Made',
    whyItMatters: 'Active word-of-mouth',
    strength: 'high',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Priority processing. Thank referrer within 24 hours. Track conversion.',
    categoryOrder: 17,
  },
  {
    signalName: 'Multi-Channel Engagement',
    whyItMatters: 'Engaged across 3+ touchpoints',
    strength: 'high',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Score as high-intent. Create unified profile and assign to AE.',
    categoryOrder: 18,
  },
  {
    signalName: 'Thought Leadership Engagement',
    whyItMatters: 'Commenting on and sharing your content',
    strength: 'medium',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'top_awareness',
    hasPlaybook: false,
    categoryOrder: 19,
  },
  {
    signalName: 'Community Question Asked',
    whyItMatters: 'Seeking peer validation',
    strength: 'medium',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 20,
  },
  {
    signalName: 'Feedback/Feature Request Submitted',
    whyItMatters: 'Invested in your product roadmap',
    strength: 'medium',
    tag: 'community_led',
    channel: 'product',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 21,
  },
  {
    signalName: 'Ambassador Program Interest',
    whyItMatters: 'Wants to formally represent your brand',
    strength: 'high',
    tag: 'community_led',
    channel: 'community',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 22,
  },
  {
    signalName: 'Cross-Sell Signal',
    whyItMatters: 'Using one product, need another',
    strength: 'high',
    tag: 'sales_led',
    channel: 'product',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Identify complementary product need. Offer bundled pricing.',
    categoryOrder: 23,
  },
  {
    signalName: 'Seasonal/Cyclical Pattern',
    whyItMatters: 'Predictable buying window approaching',
    strength: 'medium',
    tag: 'sales_led',
    channel: 'crm',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Map seasonal buying cycles. Pre-position 6-8 weeks ahead.',
    categoryOrder: 24,
  },
  {
    signalName: 'Regulatory Compliance Need',
    whyItMatters: 'Must buy due to new regulations',
    strength: 'high',
    tag: 'sales_led',
    channel: 'dark_funnel',
    funnelStage: 'bottom_conversion',
    hasPlaybook: true,
    playbook: 'Lead with compliance messaging and certifications.',
    categoryOrder: 25,
  },
  {
    signalName: 'M&A Activity',
    whyItMatters: 'Organizational change creating new needs',
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 26,
  },
  {
    signalName: 'New Executive Hire',
    whyItMatters: 'New leader brings new initiatives',
    strength: 'high',
    tag: 'sales_led',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: "Research new exec's priorities. Time outreach to day 30-60 of their tenure.",
    categoryOrder: 27,
  },
  {
    signalName: 'Funding Round Announced',
    whyItMatters: 'Fresh capital = new spending',
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Outreach within 2 weeks of announcement. Lead with growth-enablement messaging.',
    categoryOrder: 28,
  },
  {
    signalName: 'Geographic Expansion',
    whyItMatters: 'New market = new infrastructure needs',
    strength: 'medium',
    tag: 'sales_led',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: false,
    categoryOrder: 29,
  },
  {
    signalName: 'Hiring Surge',
    whyItMatters: 'Growth mode = buying mode',
    strength: 'medium',
    tag: 'sales_led',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'When 10+ relevant roles posted, trigger outreach about scaling tools.',
    categoryOrder: 30,
  },
  {
    signalName: 'Tech Stack Change',
    whyItMatters: 'Infrastructure shift = evaluation window',
    strength: 'high',
    tag: 'competitor',
    channel: 'dark_funnel',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'Offer integration assessment and migration support.',
    categoryOrder: 31,
  },
  {
    signalName: 'Content Engagement Cluster',
    whyItMatters: 'Multiple content touches in short timeframe',
    strength: 'high',
    tag: 'sales_led',
    channel: 'website',
    funnelStage: 'mid_consideration',
    hasPlaybook: true,
    playbook: 'When 5+ content pieces consumed in 7 days, this is an active buyer. Route to AE immediately.',
    categoryOrder: 32,
  },
];
